# Elasticsearch Configuration
cluster:
  name: security-cluster

node:
  name: security-node-1

path:
  data: /var/lib/elasticsearch
  logs: /var/log/elasticsearch

network:
  host: 0.0.0.0
  port: 9200

discovery:
  type: single-node

xpack:
  security:
    enabled: true
