# TheHive Configuration
play.http.secret.key: "changeme"
http.port: 9000

db {
  provider: elasticsearch
  elasticsearch {
    index: thehive
    cluster: security-cluster
    host: ["http://localhost:9200"]
    username: elastic
    password: changeme
  }
}

storage {
  provider: localfs
  localfs.directory: /opt/thehive/files
}

auth {
  providers: [
    {name: local}
  ]
}
